FROM ubuntu

RUN apt-get update -y && \
    apt-get install apache2 -y

COPY ./server/apache-virtual-host.conf /etc/apache2/sites-available

RUN a2ensite apache-virtual-host.conf

RUN a2enmod ssl
RUN a2enmod proxy
RUN a2enmod proxy_http
RUN a2enmod proxy_fcgi
RUN a2enmod proxy_balancer
RUN a2enmod proxy_wstunnel

CMD service apache2 start && /bin/bash