version: '2'

services:
  # ===========================
  fpm:
    build:
      context: ../images/
      dockerfile: Dockerfile.php.7.1
    ports:
      - 9000
    volumes:
      - ../../:/var/www/html
    depends_on:
      - database

  # ===========================
  server:
    build:
      context: ../images/
      dockerfile: Dockerfile.apache
    ports:
      - 8085:80
    volumes:
       - ../../:/var/www/html
    depends_on:
      - database
      - fpm
    tty: true

  # ===========================
  database:
    build:
      context: ../images/
      dockerfile: Dockerfile.mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
    ports:
      - 3310:3306
  # ===========================
  logstash:
    build:
      context: ../images/
      dockerfile: Dockerfile.logstash
    command: logstash -e 'input{ tcp{ port=> 9600 host=>localhost } } output{ stdout{} }'
    depends_on:
      - kibana
      - elasticsearch
    tty: true

  kibana:
    build:
      context: ../images/
      dockerfile: Dockerfile.kibana
    depends_on:
      - elasticsearch
    ports:
      - 5600
      - 5601

  elasticsearch:
    build:
      context: ../images/
      dockerfile: Dockerfile.elastic
    ports:
      - 9200
      - 9300

  rabbitmq:
    build:
      context: ../images/
      dockerfile: Dockerfile.rabbitmq
    ports:
      - 4369
      - 5671
      - 5672
      - 25672
      - 15671
      - 15672
